build with public network access

diff --git a/code_generation/values/nodejs-values.yaml b/code_generation/values/nodejs-values.yaml
--- a/code_generation/values/nodejs-values.yaml
+++ b/code_generation/values/nodejs-values.yaml
@@ -5,7 +5,9 @@ imageInitScript: |-
   yum -y install git
   cat>install_nvm.sh<<EOF
   #!/bin/bash
-  git clone https://gitee.com/mirrors/nvm.git ~/.nvm && cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`
+  # 注意build环境需要公网
+  git clone https://gitee.com/mirrors/nvm.git ~/.nvm || (echo "git clone failed" && exit 1)
+  cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`
   echo ". ~/.nvm/nvm.sh" >> ~/.bashrc
   echo "export NVM_NODEJS_ORG_MIRROR=https://npmmirror.com/mirrors/node" >> ~/.bashrc
   source ~/.bashrc
@@ -31,8 +33,13 @@ imageInitScript: |-
 
   cat>~/README<<EOF
   此应用模板在root用户下部署了nvm和node.js v20.12.2版本
-  您可以使用nvm安装其他node.js版本:
-  nvm install 版本号
+  如果您想在其他用户下部署nvm和node.js，将install_nvm.sh复制到该用户目录下，使用该用户身份执行
+  查看已安装版本：
+    nvm ls
+  您可以使用nvm安装其他node.js版本：
+    nvm install 版本号
+  切换node版本号：
+    nvm use 版本号
 
   使用下面的命令测试node.js:
   nohup node /root/node_example.js &
